version: "3.9"

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/html:/usr/share/nginx/html
    ports:
      - "8080:80"

  haproxy-1:
    image: haproxy:2.8
    volumes:
      - ./haproxy/haproxy-1.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
    # Service port
      - "8180:8080"
    # Stats port
      - "8188:8888"

  haproxy-2:
    image: haproxy:2.8
    volumes:
      - ./haproxy/haproxy-2.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
    # Service port
      - "8280:8080"
    # Stats port
      - "8288:8888"

  server-11:
    image: mendhak/http-https-echo
    ports:
      - "8011:8080"

  server-12:
    image: mendhak/http-https-echo
    ports:
      - "8012:8080"

  server-13:
    image: mendhak/http-https-echo
    ports:
      - "8013:8080"

  server-21:
    image: mendhak/http-https-echo
    ports:
      - "8221:8080"

  server-22:
    image: mendhak/http-https-echo
    ports:
      - "8222:8080"

  server-23:
    image: mendhak/http-https-echo
    ports:
      - "8223:8080"